### ISSUE TITLE
could you back port it to 1.20?

### ISSUE THREAD

**Issue by ImBehinYa** [DerJulHD/LastDeathLocation#2]
could you back port it to 1.20?

**Comment by fixyldev** [comment]
Unfortunately, back-porting version 2.0 or later to MC version 1.20 is not possible because 1.20 does not yet support the function syntax that Last Death Location 2.0 heavily relies on. For example, function macros or the `if function` subcommand. Therefore, back-porting to any version below 1.20.3 is not feasible.
