### ISSUE TITLE
You can not trigger this objective yet on trigger call.

### ISSUE THREAD

**Issue by Gian-LucaA** [DerJulHD/LastDeathLocation#4]
I might just be to stupid, but whenever any Player on my Server tries to use any of the commands e.g.` /trigger -deathmenu` they just get the Message: You can not trigger this objective yet.
The Server is a 1.21 Server with fabric installed.
Cant find out why that happens. Any help would be Appreciated :)

**Comment by fixyldev** [comment]
Okay. This shouldn't be a bug at my end. This message usually indicates that the `/scoreboard players enable` command from this data pack was not being executed yet, which it should since its tagged as `tick`.

Do you get any command suggestions when trying to execute `/trigger`. Do any of those 4 options show up? If not, then the function `ldl:src/enable_trigger` was not being executed. You could try executing this function manually. This will require operator permissions. Then those 4 options should show up. Try executing one of them. Should the menu not show up or something unexpected happen, this usually means that none of the `tick` functions in the data pack are being executed.

You also mentioned that you are running a fabric server. What mods are installed?
Are other data packs installed?

**Comment by Gian-LucaA** [comment]
So I don't get any suggestions for the `/trigger` command. Manually running the function `ldl:src/enable_trigger` will make the auto suggestion for `/trigger` available. But running them will lead me just to the same result .. not avaialble yet ... 

I have the following mods installed:
- Fabric 1.21-3.6 Advanced Backups
- antixray-fabric-1.4.2+1.21
- appleskin-fabric-mc1.21-3.0.2
- dcintegration-fabric-3.0.7.2-1.21
- fabric-api-0.100.3+1.21
- fabric-language-kotlin-1.11.0+kotlin.2.0.0
- lithium-fabric-mc1.21-0.12.5

And only two Datapacks including the last Death one:
- player health indicator 1.21

**Comment by fixyldev** [comment]
I guess I have found the problem. The other data pack `player health indicator 1.21` contains a function that is tagged as `tick` but isn't present in the data pack. I guess that Minecraft just will not execute any function tagged as `tick` then. Including the one from "Last Death Location". So you have two options to fix this.

1. Either uninstall the data pack `player health indicator 1.21` and reload with `/reload`.
2. Or fix the `player health indicator 1.21` data pack yourself by deleting the following file inside the zip archive: `tick.json` at the path `/data/minecraft/tags/function`. Also do a `/reload` just in case.

This should resolve this problem.

**Comment by Gian-LucaA** [comment]
Okay, thanks so much for the quick response! Will try that.
